using System;

namespace Exception_5
{
	class MainClass
	{
		public static void Main (string[] args)
		{
			try
			{
				object obj = "you";
				int num = (int)obj;     // InvalidCastException
				Console.WriteLine($"Результат: {num}");
			}
			catch (DivideByZeroException)
			{
				Console.WriteLine("Возникло исключение DivideByZeroException");
			}
			catch (IndexOutOfRangeException)
			{
				Console.WriteLine("Возникло исключение IndexOutOfRangeException");
			}
			catch (Exception ex)
			{
				Console.WriteLine($"Исключение: {ex.Message}");
			}  
		}
	}
}
